--VJMP-JP
INSERT OR REPLACE INTO "texts" VALUES ("100200103","Wicked Priest Chilam Sabak","If you have 5 or more cards in your hand, you can Normal Summon this card without Tributing. When this card is destroyed by battle and sent to the Graveyard: You can Special Summon this card from your Graveyard in Defense Position, and if you do, it is treated as a Tuner monster. You can only use this effect of ""Wicked Priest Chilam Sabak"" once per turn.","Normal Summon without Tribute","","","","","","","","","","","","","","","");
INSERT OR REPLACE INTO "texts" VALUES ("100200104","Galaxy Worm","When this card is Normal Summoned while you control no other monsters: You can Special Summon 1 Level 3 or lower ""Galaxy"" Effect Monster from your Deck, but its effects are negated.","","","","","","","","","","","","","","","","");
INSERT OR REPLACE INTO "texts" VALUES ("100200112","Lunalight Crimson Fox","If this card is sent to the Graveyard by a card effect: You can target 1 face-up monster your opponent controls; its ATK becomes 0 until the end of this turn. During either player's turn, when a card or effect is activated that targets a ""Lunalight"" monster(s) you control: You can banish this card from your Graveyard; negate the activation, and if you do, both players gain 1000 LP.","","","","","","","","","","","","","","","","");

--MVPC-JP
INSERT OR REPLACE INTO "texts" VALUES ("100201001","Gandora X the Dragon of Destruction","When this card is Normal or Special Summoned from the hand: You can destroy as many monsters on the field as possible (other than this card), and if you do, inflict damage to your opponent equal to the highest ATK among those destroyed monsters (your choice, if tied), and if you do that, this card's ATK becomes equal to the damage inflicted to your opponent. Once per turn, during your End Phase: Halve your LP.","Destroy and damage","Halve LP","","","","","","","","","","","","","","");
INSERT OR REPLACE INTO "texts" VALUES ("100201002","Lord Gaia The Fierce Knight","If your opponent controls a monster while you do not control a monster, you can Special Summon this card (from your hand). Once per turn, if a monster whose ATK is higher than this card’s ATK is Special Summoned to your opponent’s side of the field: You can have this card gain 700 ATK until the end of this turn.","","","","","","","","","","","","","","","","");
INSERT OR REPLACE INTO "texts" VALUES ("100201003","Lemon Magician Girl","Once per turn: You can Tribute 1 ""Magician Girl"" monster you control, except ""Lemon Magician Girl""; add 1 Spellcaster-Type monster from your Deck to your hand. Once per turn, if this card is targeted for an attack: You can Special Summon 1 Spellcaster-Type monster from your hand, then, switch the attack target to that Summoned monster, also halve that attacking monster’s ATK. The effect of the monster Special Summoned by this effect is negated.","","","","","","","","","","","","","","","","");

--???
INSERT OR REPLACE INTO "texts" VALUES ("100202002","Sacred Celtic Guard","If you have 1 or more cards in your hand, this card cannot attack. Once per turn: You can Special Summon 1 ""Celtic Guard"" monster from your hand. When this card inflicts battle damage to your opponent by attacking an opponent's monster: You can draw cards equal to the number of ""Celtic Guard"" monsters you control.","Special Summon","Draw","","","","","","","","","","","","","","");

--SR02
INSERT OR REPLACE INTO "texts" VALUES ("100302001","Felgrand, the Great Divine Dragon","If this card is Special Summoned from the Graveyard: You can target 1 monster your opponent controls or in their Graveyard; banish it, and if you do, this card gains ATK and DEF equal to the banished monster's Level/Rank x 100. If this card destroys an opponent's monster by battle: You can target 1 Level 7 or 8 Dragon-Type monster in either player's Graveyard, except ""Felgrand, the Great Divine Dragon""; Special Summon it to your side of the field.","","","","","","","","","","","","","","","","");
INSERT OR REPLACE INTO "texts" VALUES ("100302002","Paladin of Felgrand","If this card is Normal or Special Summoned: You can equip 1 Level 7 or 8 Dragon-Type monster from your hand or Deck to this card. While this card is equipped with an Equip Card, it is unaffected by other monster effects. You can Tribute this card and 1 other monster, then target 1 Level 7 or 8 Dragon-Type monster in your Graveyard; Special Summon it.","Select a Lv7/8 Dragon monster","","","","","","","","","","","","","","","");
INSERT OR REPLACE INTO "texts" VALUES ("100302003","Guardian of Felgrand","If this card is Normal or Special Summoned: You can equip 1 Level 7 or 8 Dragon-Type monster from your hand or Graveyard to this card. This card gains ATK and DEF equal to half the ATK and DEF of the monster equipped to it by this effect. You can Tribute this card and 1 other monster, then target 1 Level 7 or 8 Dragon-Type monster in your Graveyard; Special Summon it.","","","","","","","","","","","","","","","","");
INSERT OR REPLACE INTO "texts" VALUES ("100302023","Ruins of the Great Divine Dragon","While you control a Level 7 or 8 Dragon-Type monster, if a monster(s) is Special Summoned, except from the Graveyard: Negate its effects until the end of this turn (even if this card leaves the field). Once per turn: You can send 1 other face-up card you control to the Graveyard; Special Summon 1 ""Great Dragon Token"" (Dragon-Type/LIGHT/Level 1/ATK 0/DEF 0). If this card is in your Graveyard: You can send 1 Level 7 or 8 Dragon-Type monster from your hand or your side of the field to the Graveyard; add this card to your hand.","Negate Effects?","","","","","","","","","","","","","","","");
INSERT OR REPLACE INTO "texts" VALUES ("100302024","Gospel of Revival","Target 1 Level 7 or 8 Dragon-Type monster in your Graveyard; Special Summon it. If a Dragon-Type monster(s) you control would be destroyed by battle or card effect, you can banish this card from your Graveyard instead.","Banish ""Gospel of Revival"" instead?","","","","","","","","","","","","","","","");
INSERT OR REPLACE INTO "texts" VALUES ("100302123","Great Dragon Token","Summoned with the effect of ""Ruins of the Great Divine Dragon""","","","","","","","","","","","","","","","","");
