--VJMP-JP
INSERT OR REPLACE INTO "texts" VALUES ("100200103","Wicked Priest Chilam Sabak","If you have 5 or more cards in your hand, you can Normal Summon this card without Tributing. When this card is destroyed by battle and sent to the Graveyard: You can Special Summon this card from your Graveyard in Defense Position, and if you do, it is treated as a Tuner monster. You can only use this effect of ""Wicked Priest Chilam Sabak"" once per turn.","Normal Summon without Tribute","","","","","","","","","","","","","","","");
INSERT OR REPLACE INTO "texts" VALUES ("100200104","Galaxy Worm","When this card is Normal Summoned while you control no other monsters: You can Special Summon 1 Level 3 or lower ""Galaxy"" Effect Monster from your Deck, but its effects are negated.","","","","","","","","","","","","","","","","");

--MVPC-JP
INSERT OR REPLACE INTO "texts" VALUES ("100201001","Gandora X the Dragon of Destruction","When this card is Normal or Special Summoned from the hand: You can destroy as many monsters on the field as possible (other than this card), and if you do, inflict damage to your opponent equal to the highest ATK among those destroyed monsters (your choice, if tied), and if you do that, this card's ATK becomes equal to the damage inflicted to your opponent. Once per turn, during your End Phase: Halve your LP.","Destroy and damage","Halve LP","","","","","","","","","","","","","","");
INSERT OR REPLACE INTO "texts" VALUES ("100201002","Lord Gaia The Fierce Knight","If your opponent controls a monster while you do not control a monster, you can Special Summon this card (from your hand). Once per turn, if a monster whose ATK is higher than this card’s ATK is Special Summoned to your opponent’s side of the field: You can have this card gain 700 ATK until the end of this turn.","","","","","","","","","","","","","","","","");
INSERT OR REPLACE INTO "texts" VALUES ("100201003","Lemon Magician Girl","Once per turn: You can Tribute 1 ""Magician Girl"" monster you control, except ""Lemon Magician Girl""; add 1 Spellcaster-Type monster from your Deck to your hand. Once per turn, if this card is targeted for an attack: You can Special Summon 1 Spellcaster-Type monster from your hand, then, switch the attack target to that Summoned monster, also halve that attacking monster’s ATK. The effect of the monster Special Summoned by this effect is negated.","","","","","","","","","","","","","","","","");

--MVPL-JP
INSERT OR REPLACE INTO "texts" VALUES ("100202002","Sacred Celtic Guard of Noble Arms","Cannot attack unless you have no cards in your hand. Once per turn: You can Special Summon 1 ""Celtic Guard"" monster from your hand. When this attacking card inflicts battle damage to your opponent: You can draw cards equal to the number of ""Celtic Guard"" monsters you control.","Special Summon","Draw","","","","","","","","","","","","","","");